// manually generated by us from the table in https://docs.oddsblaze.com/leagues

export interface League {
  sport: string
  league: string
  id: string
  odds: boolean
  players: boolean
  teams: boolean
}
